CREATE TABLE IF NOT EXISTS `damaged_return_inspections` (
  `inspection_id` INT NOT NULL AUTO_INCREMENT,
  `return_id` INT NOT NULL,
  `return_code` VARCHAR(50) NOT NULL,
  `product_id` INT NOT NULL,
  `product_name` VARCHAR(255) NOT NULL,
  `sku` VARCHAR(100) DEFAULT NULL,
  `barcode` VARCHAR(100) DEFAULT NULL,
  `po_id` INT DEFAULT NULL,
  `po_number` VARCHAR(50) DEFAULT NULL,
  `return_qty` DECIMAL(12,2) NOT NULL DEFAULT 0,
  `reason_id` INT NOT NULL DEFAULT 0,
  `reason_name` VARCHAR(255) NOT NULL,
  `status` VARCHAR(20) NOT NULL DEFAULT 'pending',
  `new_sku` VARCHAR(100) DEFAULT NULL,
  `new_product_id` INT DEFAULT NULL,
  `cost_price` DECIMAL(12,2) DEFAULT NULL,
  `sale_price` DECIMAL(12,2) DEFAULT NULL,
  `restock_qty` DECIMAL(12,2) DEFAULT NULL,
  `defect_notes` TEXT DEFAULT NULL,
  `created_by` INT DEFAULT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `inspected_by` INT DEFAULT NULL,
  `inspected_at` DATETIME DEFAULT NULL,
  `restocked_by` INT DEFAULT NULL,
  `restocked_at` DATETIME DEFAULT NULL,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`inspection_id`),
  UNIQUE KEY `uniq_return_id` (`return_id`),
  KEY `idx_status` (`status`),
  CONSTRAINT `fk_damaged_return_returned_items` FOREIGN KEY (`return_id`) REFERENCES `returned_items` (`return_id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
